// Code generated by "enumer -type NodeType -linecomment -tags a"; DO NOT EDIT.

package runtime

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the enumer command to generate them again.
	var x [1]struct{}
	_ = x[Master-0]
	_ = x[Worker-1]
}
func (i NodeType) Values() []string {
	return []string{
		"Master",
		"Worker",
	}
}

var _NodeType_kv = map[string]int64{
	"Master": 0,
	"Worker": 1,
}

func (i NodeType) KV() map[string]int64 {
	return _NodeType_kv
}

var _NodeType_vk = map[int64]string{
	0: "Master",
	1: "Worker",
}

func (i NodeType) VK() map[int64]string {
	return _NodeType_vk
}

const _NodeType_name = "MasterWorker"

var _NodeType_index = [...]uint8{0, 6, 12}

func (i NodeType) String() string {
	if i < 0 || i >= NodeType(len(_NodeType_index)-1) {
		return "NodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeType_name[_NodeType_index[i]:_NodeType_index[i+1]]
}
