// Code generated by "stringer -type RegistryType -linecomment -trimprefix Registry"; DO NOT EDIT.

package runtime

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RegistryMaster-0]
	_ = x[RegistryEtcd-1]
	_ = x[RegistryService-2]
	_ = x[RegistryUnknown-3]
}

const _RegistryType_name = "MasterEtcdServiceUnknown"

var _RegistryType_index = [...]uint8{0, 6, 10, 17, 24}

func (i RegistryType) String() string {
	if i < 0 || i >= RegistryType(len(_RegistryType_index)-1) {
		return "RegistryType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RegistryType_name[_RegistryType_index[i]:_RegistryType_index[i+1]]
}
