// Code generated by "enumer -type WebsocketEvent -linecomment -trimprefix WsEvent"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the enumer command to generate them again.
	var x [1]struct{}
	_ = x[WsEventWelcome-0]
}
func (i WebsocketEvent) Values() []string {
	return []string{
		"Welcome",
	}
}

var _WebsocketEvent_kv = map[string]int64{
	"Welcome": 0,
}

func (i WebsocketEvent) KV() map[string]int64 {
	return _WebsocketEvent_kv
}

var _WebsocketEvent_vk = map[int64]string{
	0: "Welcome",
}

func (i WebsocketEvent) VK() map[int64]string {
	return _WebsocketEvent_vk
}

const _WebsocketEvent_name = "Welcome"

var _WebsocketEvent_index = [...]uint8{0, 7}

func (i WebsocketEvent) String() string {
	if i < 0 || i >= WebsocketEvent(len(_WebsocketEvent_index)-1) {
		return "WebsocketEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WebsocketEvent_name[_WebsocketEvent_index[i]:_WebsocketEvent_index[i+1]]
}
