// Code generated by "enumer -type ClusterState -linecomment -trimprefix ClusterState"; DO NOT EDIT.

package raftserver

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the enumer command to generate them again.
	var x [1]struct{}
	_ = x[ClusterStateNew-0]
	_ = x[ClusterStateExists-1]
}
func (i ClusterState) Values() []string {
	return []string{
		"New",
		"Exists",
	}
}

var _ClusterState_kv = map[string]int64{
	"New":    0,
	"Exists": 1,
}

func (i ClusterState) KV() map[string]int64 {
	return _ClusterState_kv
}

var _ClusterState_vk = map[int64]string{
	0: "New",
	1: "Exists",
}

func (i ClusterState) VK() map[int64]string {
	return _ClusterState_vk
}

const _ClusterState_name = "NewExists"

var _ClusterState_index = [...]uint8{0, 3, 9}

func (i ClusterState) String() string {
	if i < 0 || i >= ClusterState(len(_ClusterState_index)-1) {
		return "ClusterState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ClusterState_name[_ClusterState_index[i]:_ClusterState_index[i+1]]
}
