// Code generated by "stringer -type Method -linecomment"; DO NOT EDIT.

package ws

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Binary-0]
	_ = x[Text-1]
	_ = x[Empty-2]
}

const _Method_name = "BinaryTextEmpty"

var _Method_index = [...]uint8{0, 6, 10, 15}

func (i Method) String() string {
	if i < 0 || i >= Method(len(_Method_index)-1) {
		return "Method(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Method_name[_Method_index[i]:_Method_index[i+1]]
}
